### ISSUE TITLE
Geant4 packages on conda-forge out of data

### ISSUE THREAD

**Issue by tkittel** [conda-forge/geant4-feedstock#55]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

We really appreciate the ability to install Geant4 via conda (esp. in the conda-forge channel). It has been a game-changer :-)

But while the latest Geant4 release is 11.1.2 (actually 11.1.3 since a few hours),the geant4 package on conda-forge is still stuck on the 1 year old version 11.0.3.

As we have come to rely on conda-forge for geant4 deployment, it would be great if this can be updated (it is not super urgent right now, but obviously v11.0.3 will become increasingly outdated).

Since it seems the geant4 meta.yaml is getting the source from github, and the github geant4 repo does seem to get all the latest releases, I imagine the whole process should be automatic and handled by the conda-forge robots (at least it is the case for my own conda-forge packages).

Cheers,
Thomas

### Installed packages

```shell
Not relevant (well, the "geant4" package).
```

### Environment info

```shell
Not relevant.
```

**Comment by ckoern** [comment]
In the last years I worked on updates in case the bot failed, because for me installing Geant4 via conda was a game changer as well!
However, I am no longer working in that position and do not use Geant4 anymore. I would recommend, that you try updating the feedstock yourself (it typically is easier than compiling Geant4 correctly). All you need to do is change the versions of the packages in `recipe/meta.yaml`. A good starting point is to check in the Geant4 release notes  which version of which dependency is required. Typically, CLHEP and the datasets change between releases and need to be adjusted. The dataset feedstocks are typically updated by the bot so nothing to do there manually and CLHEP is used in ROOT aswell and thus usually already available.
It is also helpful to check the build logs from the bot to see where it failed (for 11.1.3 it hints at CLHEP being too old).

I can give it a try over the weekend for this release if you do not want or manage to do it but it would be great if someone takes this over who actively uses Geant4

**Comment by tkittel** [comment]
Thanks a lot for your reply and PR @ckoern. About the PR: Any reason for disabling python bindings? I don't actually use them, but....

Concerning the road ahead, I am a bit reluctant to get dragged in to deep if there is not upstream support from Geant4. Because it seems the setup with multiple data packages and so on could be a very fragile thing to maintain if there would be no awareness and support on the efforts from core Geant4 developers (esp. config/packaging/deployment experts). I.e. if a new type of data set was added, how would we notice (on a related note: I discovered in the past that `geant4-config --check-datasets` does not work for instance with the conda-forge package, even though the datasets are there and Geant4 uses them happily, so one can not use that command to verify that all data sets are included as expected).

Perhaps @drbenmorgan or someone else could weigh in here? Ben, let me know if you want to discuss this in more detail here or over email (I am officially a Geant4 collaboration member, but not a very active one). In the neutron scattering community we are more and more moving to using conda-forge as the one unifying deployment platform, and it would be very unfortunate to not have a great geant4 package here! :-)

**Comment by ckoern** [comment]
Unfortunately, Geant4 doesn't ship the python bindings anymore (since 11.1.0), they only reference a separate personal repository:[ koichi-murakami/g4python](https://github.com/koichi-murakami/g4python). So this would need a dedicated feedstock (and maintainer).

I agree with you, that it would be great if the Geant4 collaboration would take over maintaining this feedstock. Based on the warning in the installation guide, sadly my feeling is that the collaboration will not take over any packaged builds (brew, spack, conda, etc). 

Datasets are pinned in this feedstock to match the ones listed in the release notes. The dataset feedstocks themself are getting updates automatically. In the rare case it doesn't work, getting them to run is part of updating this feedstock. I don't know why `geant4-config` is not working correctly but exactly issues like this are the reason why it would be great if an active user would maintain the feedstock. Maybe you could ask around in your community if someone else would be willing to do that?

**Comment by tkittel** [comment]
Ok, thanks for the explanation @ckoern, if upstream dropped python bindings then of course they had to go.

And as I said, I am not necessarily unwilling to help out maintain this feedstock, but I would like to do it with a mutual understanding with core upstream (e.g. @drbenmorgan), to prevent surprises and misunderstandings in both directions.

**Comment by drbenmorgan** [comment]
> Perhaps @drbenmorgan or someone else could weigh in here? Ben, let me know if you want to discuss this in more detail here or over email (I am officially a Geant4 collaboration member, but not a very active one). In the neutron scattering community we are more and more moving to using conda-forge as the one unifying deployment platform, and it would be very unfortunate to not have a great geant4 package here! :-)

@tkittel sorry for the delay in responding... I'm very happy to discuss this further as packaging is something Geant4 wants to support more. As with all things, it's been lack of available time/effort to devote formal support here. If we have >1 maintainer and a clearly documented procedure/automatization, then this becomes more feasible.

Maybe let's continue discussion here, or in a fresh issue, so that we can ping others if needed.
